version: '2'

networks: 
    my-network1:

services: 
    php-fpm:
        build: php-fpm
        networks: 
            - my-network1
        depends_on: 
            - mysql-db
            - redis-db
        volumes:
            - ./php-fpm/www:/app
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    
    nginx:
        image: nginx
        networks:
            - my-network1
        depends_on: 
            - php-fpm
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/html:/var/www/html
            - ./nginx/log:/var/log/nginx
        ports: 
            - "80:80"
            - "443:443"

    mysql:
        image: mysql:5.7.22
        networks: 
            - my-network1
        volumes: 
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports: 
            - "3306:3306"
    
    redis-db:
        image: redis:5.0
        networks: 
            - my-network1
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data