version: '2'

networks: 
    my-network1:
        driver: bridge

services: 
    php-fpm:
        container_name: zler-php-fpm
        image: php:7.3-fpm
        restart: always
        networks: 
            - my-network1
        depends_on: 
            - mysql
            - redis
        volumes:
            - ./php-fpm/www:/var/www/html
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php-fpm/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
       
    nginx:
        container_name: zler-nginx
        image: nginx
        restart: always
        networks:
            - my-network1
        depends_on: 
            - php-fpm
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/html:/var/www/html
            - ./nginx/log:/var/log/nginx
        ports: 
            - "80:80"
            - "443:443"

    mysql:
        container_name: zler-mysql
        image: mysql:5.7.22
        restart: always
        networks: 
            - my-network1
        volumes: 
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports: 
            - "3306:3306"
    
    redis:
        container_name: zler-redis
        image: redis:5.0.0
        restart: always
        networks: 
            - my-network1
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data
    
    elasticsearch:
        container_name: zler-elasticsearch
        image: elasticsearch:5.5.1
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        networks: 
             - my-network1
        ports: 
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins