version: '2'

networks: 
    my-network1:
        driver: bridge

services: 
    php-fpm:
        container_name: zler-php-fpm
        image: php:7.3-fpm
        networks: 
            - my-network1
        depends_on: 
            - mysql
            - redis
        volumes:
            - ./php-fpm/www:/var/www/html
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php-fpm/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
       
    nginx:
        container_name: zler-nginx
        image: nginx
        networks:
            - my-network1
        depends_on: 
            - php-fpm
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/html:/var/www/html
            - ./nginx/log:/var/log/nginx
        ports: 
            - "80:80"
            - "443:443"

    mysql:
        container_name: zler-mysql
        image: mysql:5.7.22
        networks: 
            - my-network1
        volumes: 
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports: 
            - "3306:3306"
    
    redis:
        container_name: zler-redis
        image: redis:5.0.0
        networks: 
            - my-network1
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data